blank_issues_enabled: true
contact_links:
  - name: 💬 Question / Discussion
    url: https://github.com/DSestu/python-project-template/discussions
    about: Ask a question or discuss an idea instead of opening an issue.
